---
title: "Indíce de Ensino à Distância - IEAD"
format: html
editor: visual
---


<style>
body {
text-align: justify}
</style>

```{r, echo=FALSE}
knitr::opts_chunk$set(echo=F, error=FALSE, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE}
# Pacotes

if (!require("pacman")) install.packages("pacman"); 
pacman::p_load("tidyverse", "dplyr", "ggthemes", "sf",
               "lwgeom", "rgdal", "tmaptools", "mapview", "raster",
               "viridis", "patchwork", "ggpubr", "readxl", "haven",
               "lubridate")


#Pacotes geobr
if (!require("devtools")) install.packages("devtools")

  devtools::install_github("ipeaGIT/geobr", subdir = "r-package")
  library(geobr)
```

Neste post, irei falar um pouco sobre o índice IEAD e como ele foi calculado...

```{python}
import plotly as plt
import plotly.express as px
import json
from urllib.request import urlopen
import pandas as pd
```


```{python}

with urlopen('https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/brazil-states.geojson') as response:
    Brazil = json.load(response)
```

```{python}
state_id_map = {}

for feature in Brazil['features']:
    feature['id'] = feature['properties']['name']
    state_id_map[feature['properties']['sigla']] = feature['id']
    
```


```{python}
df = pd.read_csv("IEAD.csv")

df.head()
```

```{python}

fig = px.choropleth(
df,
locations = "Estado",
geojson= Brazil,
color = "IEAD_médio",
labels = {"IEAD_médio":"IEAD Médio", 
          "ano":"Ano"},
color_continuous_scale="aggrnyl",  # haline
range_color=(0, 10),
hover_name="Estado",
hover_data=['IEAD_médio'],
title="IEAD Médio por ano",
animation_frame="ano")

fig.update_geos(fitbounds= "locations", visible = False)

fig.write_html("myplot.html")
```





